/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as FsRouteImport } from './routes/fs'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as IndexRouteImport } from './routes/index'

const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const FsRoute = FsRouteImport.update({
  id: '/fs',
  path: '/fs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/fs': typeof FsRoute
  '/graph': typeof GraphRoute
  '/ingest': typeof IngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/fs': typeof FsRoute
  '/graph': typeof GraphRoute
  '/ingest': typeof IngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/fs': typeof FsRoute
  '/graph': typeof GraphRoute
  '/ingest': typeof IngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conflicts' | '/fs' | '/graph' | '/ingest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conflicts' | '/fs' | '/graph' | '/ingest'
  id: '__root__' | '/' | '/conflicts' | '/fs' | '/graph' | '/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConflictsRoute: typeof ConflictsRoute
  FsRoute: typeof FsRoute
  GraphRoute: typeof GraphRoute
  IngestRoute: typeof IngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fs': {
      id: '/fs'
      path: '/fs'
      fullPath: '/fs'
      preLoaderRoute: typeof FsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConflictsRoute: ConflictsRoute,
  FsRoute: FsRoute,
  GraphRoute: GraphRoute,
  IngestRoute: IngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
